DROP TABLE IF EXISTS `GENERAL`;

CREATE TABLE `GENERAL`(
	`G_ID` VARCHAR(36) NOT NULL,
	`G_CODE` VARCHAR(100) DEFAULT NULL,
	`G_DESC` LONGTEXT DEFAULT NULL,
	`G_INSERT_DATE` DATETIME DEFAULT NULL, 
	PRIMARY KEY (`G_ID`)
)