DROP TABLE IF EXISTS `IP_USER`;

CREATE TABLE `IP_USER`(
	`IU_ID` VARCHAR(36) NOT NULL,
	`IU_IP` VARCHAR(100) DEFAULT NULL,
	`IU_CITY` VARCHAR(100) DEFAULT NULL,
	`IU_REGION` VARCHAR(100) DEFAULT NULL,
	`IU_COUNTRY` VARCHAR(100) DEFAULT NULL, 
	`IU_POSTAL` VARCHAR(100) DEFAULT NULL,
	`IU_LATITUDE` DOUBLE(10,4) DEFAULT NULL, 
	`IU_LONGITUDE` DOUBLE(10,4) DEFAULT NULL,
	`IU_INTERNET_PROVIDER` VARCHAR(100) DEFAULT NULL,
	`IU_INSERT_DATE` DATETIME DEFAULT NULL, 
	PRIMARY KEY (`IU_ID`)

)