DROP TABLE IF EXISTS `JOB` 

CREATE TABLE `JOB`(
	
	`J_ID` VARCHAR(36) NOT NULL, 
	`J_NAME` VARCHAR(100) DEFAULT NULL, 
	`J_TITLE` VARCHAR(100) DEFAULT NULL,
	`J_YEAR` VARCHAR(100) DEFAULT NULL,
	`J_ACTIVE` VARCHAR(1) DEFAULT NULL,
	`J_INSERT_DATE` DATE DEFAULT NULL,
	PRIMARY KEY(`E_ID`)
)