DROP TABLE IF EXISTS `JOB_DETAIL`;

CREATE TABLE `JOB_DETAIL`(
	
	`JD_ID` VARCHAR(36) NOT NULL, 
	`JD_J_ID` VARCHAR(36) NOT NULL,
	`JD_PROJECT` VARCHAR(100) NOT NULL,
	`JD_POST` BLOB,
	`JD_ACTIVE` VARCHAR(1) DEFAULT NULL,
	`JD_INSERT_DATE` DATETIME DEFAULT NULL,
	PRIMARY KEY(`JD_ID`),
	FOREIGN KEY(`JD_J_ID`) REFERENCES `JOB`(`J_ID`)
)