DROP TABLE IF EXISTS `MAIN_USER`;

CREATE TABLE `MAIN_USER` (
	`MU_ID` 	VARCHAR(36) NOT NULL,
    `MU_USERNAME` VARCHAR(100) DEFAULT NULL, 
    `MU_PASSWORD` CHAR(100) DEFAULT NULL, 
    `MU_TOKEN` VARCHAR(100) DEFAULT NULL,
    `MU_ROLE` VARCHAR(200) DEFAULT NULL,
    `MU_ACTIVE` VARCHAR(1) DEFAULT NULL, 
    `MU_INSERT_DATE` DATETIME DEFAULT NULL,
    PRIMARY KEY (`MU_ID`)
)