DROP TABLE IF EXISTS `PROFILE`;

CREATE TABLE `PROFILE`(
	`P_ID` VARCHAR(36) NOT NULL, 
	`P_TYPE` VARCHAR(100) DEFAULT NULL, 
	`P_NAME` VARCHAR(100) DEFAULT NULL, 
	`P_SVG` VARCHAR(100) DEFAULT NULL, 
	`P_IMAGE` BLOB,
	`P_ACTIVE` VARCHAR(1) DEFAULT NULL, 
	`P_INSERT_DATE` DATETIME DEFAULT NULL,
	PRIMARY KEY(`P_ID`)
)