DROP TABLE IF EXISTS `EDUCATION`;

CREATE TABLE `EDUCATION`(
	
	`E_ID` VARCHAR(36) NOT NULL, 
	`E_NAME` VARCHAR(100) DEFAULT NULL, 
	`E_COURSE` VARCHAR(100) DEFAULT NULL,
	`E_YEAR` VARCHAR(100) DEFAULT NULL,
	`E_IMAGE` longblob DEFAULT NULL,
	`E_ACTIVE` VARCHAR(1) DEFAULT NULL,
	`E_INSERT_DATE` DATETIME DEFAULT NULL,
	PRIMARY KEY(`E_ID`)
)