DROP TABLE IF EXISTS `TECH`;

CREATE TABLE `TECH` (
	`T_ID` 	VARCHAR(36) NOT NULL,
    `T_TYPE` VARCHAR(100) DEFAULT NULL, 
    `T_SEQ` INT DEFAULT NULL,
    `T_NAME` VARCHAR(100) DEFAULT NULL, 
    `T_SVG` VARCHAR(200) DEFAULT NULL,
    `T_ACTIVE` VARCHAR(1) DEFAULT NULL, 
    `T_INSERT_DATE` DATETIME DEFAULT NULL,
    PRIMARY KEY (`T_ID`)
)